#**************** Logistic Regression *************************************#
#**************************************************************************#

getwd()
setwd("C:\\Users\\Suruthi\\Desktop\\Data\\Logistic Regression\\Input")


# --------Importing Data--------
data=read.csv("Attrdata.csv")


# ----Correlation Matrix-------
cor_matrix=cor(data)
write.csv(cor_matrix,file="cor.csv")


# By looking through the correlation matrix, we came to know that the
# variable "NO_OF_SUPV_CHG_2014_OTHERS" contains no value (all zero's)
# So excluding the most insignificant variable
# NO_OF_SUPV_CHG_2014_OTHERS
data<-subset( data, select = -c(NO_OF_SUPV_CHG_2014_OTHERS) )

# -----Splitting Data------
set.seed(123)
d=sort(sample(nrow(data), nrow(data)*.7)) 

#select training and test sample 
train<-data[d,] 
test<-data[-d,]


# -----Bivariate-----
Bivar_analy<-matrix(NA,2,2)
#names(Bivar_analy)[2]<-paste("pval")
for(i in 3:ncol(train)){
  mod<-glm(Response~train[,i],data=train,family=binomial)
pval<-summary(mod)$coefficients[2,4]
Bivar<-as.data.frame(cbind(names(train[i]),pval))
Bivar_analy<-rbind(as.matrix(Bivar),Bivar_analy)
}
write.csv(Bivar_analy,file = "BivariateAnalysis_Me.csv")
# We got 63 significant variables after Bivariate Analysis. 
# with these we can perform vif on it.

#Ind_Var=colnames(train[3:ncol(train)])
#final <- matrix(NA,2,5)
# -----Bivariate-----
#for (i in 3:ncol(train)){
#  v1=glm(Response~train[,i],data=train,family=binomial)
#  s1 <-summary(v1)$coefficients
#  category <- as.data.frame(rep((Ind_Var)[i-2],nrow(s1)))
#  summary <- cbind(category,s1)
#  names(summary)[1]=paste("Variable")
#  final <- rbind(as.matrix(summary),final)
#}
#write.csv(final,file="Bivariate.csv")

install.packages("rlang")
install.packages("tibble")
#***************
# -----VIF- Variance Inflation Factor-----
#***************
install.packages("car")
library(car)
# Step-1
model_vif<-glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_STATE_CALIFORNIA+WORK_STATE_KARNATAKA+WORK_SITE_SANJOSE+WORK_SITE_BNG+WORK_REGION_EMEA+WORK_REGION_APJC+WORK_LOCATION_OTHERS+WORK_LOCATION_BNG+WORK_LOCATION_US_CALIFORNIA+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+TOTAL_PROMO_OTHERS+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+REVIEW_RTG_OUTSTANDING+REVIEW_RTG_NOT_RATED+REVIEW_RTG_EXCEPTIONAL+REVIEW_RTG_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_UNKNOWN+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_2014_3_7+NO_OF_SUPV_CHG_GRP_UNKNOWN+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+MNG_LOC_LOC+JOBTITLE_GRP_OTHER+JOBTITLE_GRP_ENG+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
vif(model_vif)
#model_vif=glm(Response~AGE_25_30+AGE_31_35+AGE_36_40+AGE_41_45+AGE_46_50+AGE_GT_50+BONUS_008+BONUS_015+BONUS_GTE_025+BONUS_LTE_007+COMP_RATION_1_119+COMP_RATION_GT_119+COMP_RATIO_08_089+COMP_RATIO_09_099+COMP_RATIO_LT_08+COUNTRY_INDIA+COUNTRY_OTHERS+COUNTRY_US+ETHNIC_GRP_1+ETHNIC_GRP_4+ETHNIC_GRP_UNKNOWN+GENDER_M+GRADE_GRP_10+GRADE_GRP_11+GRADE_GRP_12+GRADE_GRP_1_5+GRADE_GRP_6_7+JOBTITLE_GRP_OTHER+LOA_DAYS_GRP_UNKNOWN+MANAGER_LEVEL_IC+MARITAL_STATUS_S+MARITAL_STATUS_U+MARITAL_STATUS_UNKNOWN+MILITARY_STATUS_NOT_VETERAN+MNG_LOC_LOC+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_2014_UNKNOWN+NO_OF_SUPV_CHG_GRP_3_5+NO_OF_SUPV_CHG_GRP_6_7+NO_OF_SUPV_CHG_GRP_8_10+NO_OF_SUPV_CHG_GRP_LT_3+NO_OF_SUPV_CHG_GRP_UNKNOWN+ORG_NAME_ENG+ORG_NAME_SALES+ORG_NAME_SERV+REVIEW_RTG_EXCEPTIONAL+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_STRONG+REVIEW_RTG_NOT_RATED+REVIEW_RTG_OUTSTANDING+REVIEW_RTG_STRONG+TOTAL_PROMO_GRP_LT_3+TOTAL_PROMO_UNKNOWN+WORK_LOCATION_BNG+WORK_LOCATION_US_CALIFORNIA+WORK_REGION_APJC+WORK_REGION_EMEA+WORK_SITE_BNG+WORK_SITE_SANJOSE+WORK_STATE_CALIFORNIA+WORK_STATE_KARNATAKA+WORK_TYPE_MOBILE_WORKER+WORK_TYPE_TRADITIONAL+YRS_GRADE_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_4_5999+YRS_GRADE_RANGE_6_9999+YRS_GRADE_RANGE_LT_1+YRS_IN_JOB_RANGE_1_1999+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_4_5999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_SERVICE_RANGE_1_1999+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_6_9999+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_LT_1+YRS_SINCE_LAST_PROMO_3_499+YRS_SINCE_LAST_PROMO_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_SAL_CHG_GE_3+YRS_SINCE_LAST_SAL_CHG_LT_3,data=train,family=binomial)
# Error in vif.default(model_vif) : 
# Identifying alias coefficients:
alias(model_vif)
# alaias fuction gave us 13 variable that are completely derivable from other variables.
# These variables we can neglect from the model and proceed with other variables.

# Step-1 (after eliminating alias coeficients)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_STATE_CALIFORNIA+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+WORK_LOCATION_OTHERS+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_UNKNOWN+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif1.csv")

# Step-2  (eliminating YRS_SINCE_LAST_PROMO_LT_3)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_STATE_CALIFORNIA+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+WORK_LOCATION_OTHERS+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_UNKNOWN+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif2.csv")

# Step-3 (eliminating WORK_STATE_CALIFORNIA)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+WORK_LOCATION_OTHERS+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_UNKNOWN+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif3.csv")


# Step-4 (eliminating NO_OF_SUPV_CHG_2014_UNKNOWN)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+WORK_LOCATION_OTHERS+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif4.csv")

# Step-5 (eliminating WORK_LOCATION_OTHERS)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+YRS_GRADE_RANGE_1_1999+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif5.csv")

# Step-6 (eliminating YRS_GRADE_RANGE_1_1999)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_2_3999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif6.csv")

# Step-7 (eliminating YRS_IN_JOB_RANGE_2_3999)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_STATE_OTHERS+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif7.csv")


# Step-8 (eliminating WORK_STATE_OTHERS)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_UNKNOWN+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif8.csv")


# Step-9 (eliminating TOTAL_PROMO_UNKNOWN)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_GTE_025+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif9.csv")


# Step-10 (eliminating BONUS_GTE_025)
 
model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_LT_1+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif10.csv")

# Step-11 (eliminating YRS_IN_JOB_RANGE_LT_1)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+WORK_REGION_APJC+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif11.csv")

# Step-12 (eliminating WORK_REGION_APJC)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+COUNTRY_INDIA+COUNTRY_OTHERS+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif12.csv")

# Step-13 (eliminating COUNTRY_OTHERS)

model_vif=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+COUNTRY_INDIA+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
s <- vif(model_vif)
write.csv(s,file="vif13.csv")

# Finally reached a model, where all the variables have a VIF value less than 2.5.
# Totally we have 37 variables at the end of the VIF model.


# -----Stepwise Selection---- 
install.packages("stats")
library(stats)
model_test=glm(Response~YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_SERVICE_RANGE_2_3999+YRS_IN_SERVICE_RANGE_10_14999+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_TYPE_MOBILE_WORKER+WORK_SITE_SANJOSE+WORK_REGION_EMEA+COUNTRY_INDIA+TOTAL_PROMO_GRP_LT_3+REVIEW_RTG_LTR_OUTSTANDING+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_EXCEPTIONAL+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+ORG_NAME_SALES+NO_OF_SUPV_CHG_2014_LT_3+NO_OF_SUPV_CHG_GRP_GT_10+MARITAL_STATUS_S+MARITAL_STATUS_M+MNG_LOC_REM+JOBTITLE_GRP_OTHER+GRADE_GRP_12+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_015+BONUS_LTE_007+COMP_RATION_GT_119+COMP_RATION_1_119+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_25_30+AGE_LT_25,data=train,family=binomial)
model_step=step(model_test)
s=summary(model_step)
write.csv(s$coefficients,file="stepwise.csv")

# Stepwise selection gave us 21 variables as the most significant variables. 
# with these we can run our final model on the 21 most significant variables.

# -----Final Model---------
model_final=glm(Response ~ YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_SITE_SANJOSE+WORK_REGION_EMEA+COUNTRY_INDIA+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+MARITAL_STATUS_S+GRADE_GRP_10+GRADE_GRP_1_5+BONUS_LTE_007+COMP_RATIO_08_089+AGE_GT_50+AGE_46_50+AGE_LT_25,data=train,family=binomial)
s1 <-summary.glm(model_final)$coefficients
write.csv(s1,file="final_coff.csv")

# On running the final model on 21 most significant variables given by stepwise selection
# Final model gave 16 variables with pvalue less than 0.05. Rerunning the final model with 16 variables.

# -----Rerun  the Final Model with most significant variables---------
model_final=glm(Response ~ YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_SITE_SANJOSE+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+GRADE_GRP_1_5+BONUS_LTE_007+COMP_RATIO_08_089+AGE_GT_50+AGE_LT_25,data=train,family=binomial)
s1 <-summary.glm(model_final)$coefficients
write.csv(s1,file="rerunfinal_coff.csv")

model_final

# --------Concordance and Discordance----------
OptimisedConc=function(model)
{
  Data = cbind(model$y, model$fitted.values) 
  ones = Data[Data[,1] == 1,]
  zeros = Data[Data[,1] == 0,]
  conc=matrix(0, dim(zeros)[1], dim(ones)[1])
  disc=matrix(0, dim(zeros)[1], dim(ones)[1])
  ties=matrix(0, dim(zeros)[1], dim(ones)[1])
  for (j in 1:dim(zeros)[1])
  {
    for (i in 1:dim(ones)[1])
    {
      if (ones[i,2]>zeros[j,2])
      {conc[j,i]=1}
      else if (ones[i,2]<zeros[j,2])
      {disc[j,i]=1}
      else if (ones[i,2]==zeros[j,2])
      {ties[j,i]=1}
    }
  }
  Pairs=dim(zeros)[1]*dim(ones)[1]
  PercentConcordance=(sum(conc)/Pairs)*100
  PercentDiscordance=(sum(disc)/Pairs)*100
  PercentTied=(sum(ties)/Pairs)*100
  return(list("Percent Concordance"=PercentConcordance,"Percent Discordance"=PercentDiscordance,"Percent Tied"=PercentTied,"Pairs"=Pairs))}

OptimisedConc(model_final)

# -----fitted values------
train$predicted=predict(model_final,train,type="response")
write.csv(train,file="data_fitted_train.csv")


# ROC Curve
install.packages("pROC")
library(pROC)
plot(roc(train$Response, train$predicted, direction="<"),
     col="red", lwd=3, main="The turtle finds its way")

# --------same model running on validation sample--------------
model_final_test=glm(Response ~ YRS_SINCE_LAST_SAL_CHG_LT_3+YRS_SINCE_LAST_PROMO_OTHERS+YRS_SINCE_LAST_PROMO_3_499+YRS_IN_SERVICE_RANGE_GTE_15+YRS_IN_JOB_RANGE_1_1999+YRS_GRADE_RANGE_2_3999+YRS_GRADE_RANGE_LT_1+WORK_SITE_SANJOSE+REVIEW_RTG_LTR_NOT_RATED+REVIEW_RTG_LTR_OTHERS+ORG_NAME_ENG+GRADE_GRP_1_5+BONUS_LTE_007+COMP_RATIO_08_089+AGE_GT_50+AGE_LT_25,data=test,family=binomial)
summary(model_final_test)

# --------Concordance and Discordance----------
OptimisedConc=function(model)
{
  Data = cbind(model$y, model$fitted.values) 
  ones = Data[Data[,1] == 1,]
  zeros = Data[Data[,1] == 0,]
  conc=matrix(0, dim(zeros)[1], dim(ones)[1])
  disc=matrix(0, dim(zeros)[1], dim(ones)[1])
  ties=matrix(0, dim(zeros)[1], dim(ones)[1])
  for (j in 1:dim(zeros)[1])
  {
    for (i in 1:dim(ones)[1])
    {
      if (ones[i,2]>zeros[j,2])
      {conc[j,i]=1}
      else if (ones[i,2]<zeros[j,2])
      {disc[j,i]=1}
      else if (ones[i,2]==zeros[j,2])
      {ties[j,i]=1}
    }
  }
  Pairs=dim(zeros)[1]*dim(ones)[1]
  PercentConcordance=(sum(conc)/Pairs)*100
  PercentDiscordance=(sum(disc)/Pairs)*100
  PercentTied=(sum(ties)/Pairs)*100
  return(list("Percent Concordance"=PercentConcordance,"Percent Discordance"=PercentDiscordance,"Percent Tied"=PercentTied,"Pairs"=Pairs))}

OptimisedConc(model_final_test)


# -----fitted values------
test$predicted=predict(model_final_test,test,type="response")
write.csv(test,file="data_fitted_test.csv")

# ROC Curve
plot(roc(test$Response, test$predicted, direction="<"),
     col="red", lwd=3, main="The turtle finds its way")

# ----Scores Generation-------------------------
score= read.csv("active.csv")

score$predicted=predict(model_final,score,type="response")

write.csv(score,file="scores.csv")
